#!/bin/sh

if [ "$1" = "pedantic" ]
then 
	export CXXFLAGS="-g -O2 -ansi -pedantic -Wall -W -Wold-style-cast -Wfloat-equal -Wwrite-strings -Woverloaded-virtual -Wno-long-long"
	shift
fi

rm -f config.cache
set -x

bakefilize &&
	bakefile -f autoconf mysql++.bkl &&
	bakefile -f autoconf lib/lib.bkl &&
	bakefile -f autoconf examples/examples.bkl &&
	autoreconf -i &&
	aclocal -I config &&
	autoheader &&
	autoconf &&
	./reconf $* &&
	( cd lib ; make custom.h )

#! Add bakefile calls to generate simple GCC makefile (for examples
#! dir in RPM) and VC++ project files.  Also consider MinGW support.
