#!/bin/sh

if [ "$1" = "pedantic" ]
then 
	export CXXFLAGS="-g -O2 -ansi -pedantic -Wall -W -Wold-style-cast -Wfloat-equal -Wwrite-strings -Woverloaded-virtual -Wno-long-long"
	shift
fi

rm -f config.cache
set -x

./rebake &&
	aclocal -I config -I /usr/local/share/aclocal &&
	autoheader &&
	autoconf &&
	./reconf $* &&
	( cd lib ; make custom.h )

