#!/bin/sh
if [ $# -lt 1 ]
then
	echo usage: mkbf format
	echo
	echo "   Runs bakefile with the given -f argument for this"
	echo "   project's various Bakefiles."
	echo
	exit 1
fi

bakefile -f $1 mysql++.bkl &&
		bakefile -f $1 lib/lib.bkl &&
		bakefile -f $1 examples/examples.bkl

